const BASE = process.env.SHIPCOM_API_BASE || 'https://app.ship.com';
function token(){const t=process.env.SHIPCOM_ACCESS_TOKEN;if(!t)throw new Error('Missing SHIPCOM_ACCESS_TOKEN');return t}
async function shipFetch(path, options={}){const res=await fetch(`${BASE}${path}`,{...options,headers:{Authorization:`Bearer ${token()}`,'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});const text=await res.text();let data;try{data=text?JSON.parse(text):{}}catch{data={raw:text}}if(!res.ok)throw new Error(`Ship.com API failed: ${res.status} ${typeof data==='object'?JSON.stringify(data):text}`);return data}
export function buildShipcomOrderPayload(order={}){return {customer:{name:order.customer_name,email:order.customer_email,phone:order.customer_phone},shipTo:{name:order.customer_name,street1:order.address_line1,street2:order.address_line2,city:order.city,state:order.state,zip:order.zip,country:order.country||'US'},package:{weight:order.parcel_weight,weightUnit:order.weight_unit||'oz',length:order.parcel_length,width:order.parcel_width,height:order.parcel_height},notes:order.notes||''}}
export async function createShipcomOrder(order){const path=process.env.SHIPCOM_CREATE_ORDER_PATH||'/public/orders';return shipFetch(path,{method:'POST',body:JSON.stringify(buildShipcomOrderPayload(order))})}
export async function getShipcomRates(order){const path=process.env.SHIPCOM_RATES_PATH||'/public/rates';return shipFetch(path,{method:'POST',body:JSON.stringify({orderID:order.shipcom_order_id||order.orderID,package:buildShipcomOrderPayload(order).package,shipDate:order.ship_date})})}
export async function purchaseShipcomLabel(order, rate={}){const path=process.env.SHIPCOM_PURCHASE_LABEL_PATH||'/public/purchase-label';const body={orderID:order.shipcom_order_id||order.orderID,rateID:rate.rateID||rate.id||order.rate_id,packageID:rate.packageID||order.package_id,shippingMethod:rate.shippingMethod||order.carrier,serviceLevel:rate.serviceLevel||order.mail_class,shipDate:order.ship_date,signature:!!order.require_signature,insurance:!!order.insurance_enabled,insureShipping:!!order.insure_shipping,insuredValue:order.insured_value,additionalHandlingUPS:!!order.additional_handling_ups,saturdayDeliveryUPS:!!order.saturday_delivery_ups,packageTypeUPS:order.package_type_ups,weight:order.parcel_weight,printerType:order.printer_type};return shipFetch(path,{method:'POST',body:JSON.stringify(body)})}
export async function refundShipcomLabel(order){const path=process.env.SHIPCOM_REFUND_LABEL_PATH||'/public/refund-label';return shipFetch(path,{method:'POST',body:JSON.stringify({labelID:order.shipcom_label_id,trackingNumber:order.tracking_number,orderID:order.shipcom_order_id})})}
export function normalizeLabelResponse(data={}, order={}){return {shipcom_order_id:data.orderID||data.orderId||data.order_id||order.shipcom_order_id||'',shipcom_label_id:data.labelID||data.labelId||data.label_id||'',tracking_number:data.trackingNumber||data.tracking_number||data.tracking||'',tracking_url:data.trackingURL||data.trackingUrl||data.tracking_url||'',label_url:data.shippingLabelURL||data.labelURL||data.label_url||data.labelUrl||'',carrier:data.carrier||order.carrier||'',mail_class:data.serviceLevel||data.mailClass||order.mail_class||'',shipment_date:order.ship_date||new Date().toISOString().slice(0,10),status:'label_created'}}
