const url=process.env.NEXT_PUBLIC_SUPABASE_URL;
const key=process.env.SUPABASE_SERVICE_ROLE_KEY;
function headers(extra={}){if(!url||!key)throw new Error('Missing Supabase env vars');return {apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=representation',...extra}}
function endpoint(path){return `${url}/rest/v1/${path}`}
export async function selectOrders(){const res=await fetch(endpoint('shipping_orders?select=*&order=created_at.desc'),{headers:headers(),cache:'no-store'});if(!res.ok)throw new Error(await res.text());return res.json()}
export async function selectCustomers(){const orders=await selectOrders();const map=new Map();for(const o of orders){const k=(o.customer_email||o.customer_phone||o.customer_name||'Unknown').toLowerCase();if(!map.has(k))map.set(k,{...o,orders:[]});map.get(k).orders.push(o)}return Array.from(map.values()).sort((a,b)=>(a.customer_name||'').localeCompare(b.customer_name||''))}
export async function createOrder(row){const body={...row,customer_address:row.customer_address||[row.address_line1,row.address_line2,[row.city,row.state,row.zip].filter(Boolean).join(', ')].filter(Boolean).join('\n'),updated_at:new Date().toISOString()};const res=await fetch(endpoint('shipping_orders'),{method:'POST',headers:headers(),body:JSON.stringify([body])});if(!res.ok)throw new Error(await res.text());const rows=await res.json();return rows[0]}
export async function updateOrder(id, patch){const res=await fetch(endpoint(`shipping_orders?id=eq.${id}`),{method:'PATCH',headers:headers(),body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!res.ok)throw new Error(await res.text());const rows=await res.json();return rows[0]}
export async function upsertOrder(row){if(row.id)return updateOrder(row.id,row);const conflict=row.tracking_number?'tracking_number':'id';const res=await fetch(endpoint(`shipping_orders?on_conflict=${conflict}`),{method:'POST',headers:headers({Prefer:'resolution=merge-duplicates,return=representation'}),body:JSON.stringify([row])});if(!res.ok)throw new Error(await res.text());const rows=await res.json();return rows[0]}
export async function updateCustomer(match, patch){const orders=await selectOrders();const rows=orders.filter(o=>(o.customer_email&&o.customer_email===match)||(o.customer_phone&&o.customer_phone===match)||o.customer_name===match);for(const o of rows){await updateOrder(o.id,patch)}return selectCustomers()}
