create table if not exists shipping_orders (
  id uuid primary key default gen_random_uuid(),
  customer_name text,
  customer_email text,
  customer_phone text,
  customer_address text,
  address_line1 text,
  address_line2 text,
  city text,
  state text,
  zip text,
  country text default 'US',
  parcel_weight text,
  weight_unit text default 'oz',
  parcel_length text,
  parcel_width text,
  parcel_height text,
  printer_type text,
  ship_date text,
  require_signature boolean default false,
  saturday_delivery_ups boolean default false,
  additional_handling_ups boolean default false,
  insurance_enabled boolean default false,
  insure_shipping boolean default false,
  insured_value text,
  package_type_ups text,
  notes text,
  shipcom_order_id text,
  shipcom_label_id text,
  carrier text,
  mail_class text,
  tracking_number text unique,
  tracking_url text,
  label_url text,
  shipment_date text,
  status text default 'draft',
  source text default 'shipcom',
  notification_sent boolean default false,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

alter table shipping_orders add column if not exists refund_response text;
alter table shipping_orders add column if not exists batch_id text;
